import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import "@/styles/globals.css";
import { ThemeProvider } from '@/providers/ThemeProvider';
import { AuthProvider } from '@/providers/AuthContext';
import { Inter } from 'next/font/google'
import { cn } from "@/lib/utils"
import { AnimatedGridPattern } from "@/components/ui/animated-grid-pattern"
import { Toaster } from "@/components/ui/sonner"

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-sans',
})

export default async function RootLocaleLayout({ children, params }) {
    const { locale } = await params;

    if (!routing.locales.includes(locale)) {
        notFound();
    }

    const messages = await getMessages();

    return (
        <html lang={locale} className={`${inter.variable}`} suppressHydrationWarning>
            <body>
                <NextIntlClientProvider messages={messages}>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <AuthProvider>
                            <AnimatedGridPattern
                                numSquares={40}
                                maxOpacity={0.1}
                                duration={3}
                                repeatDelay={1}
                                className={cn(
                                    "[mask-image:radial-gradient(1000px_circle_at_center,white,transparent)]",
                                    "fixed inset-0 z-[-1] h-full w-full skew-y-12"
                                )}
                            />
                            {children}
                            <Toaster />
                        </AuthProvider>
                    </ThemeProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}